//go:build tools
package main
import (
  _ "github.com/caddyserver/caddy/v2"
  _ "github.com/caddyserver/forwardproxy"
  _ "github.com/imgk/caddy-trojan"
  _ "github.com/mholt/caddy-l4"
  _ "github.com/caddyserver/jsonc-adapter"
  _ "github.com/greenpau/caddy-security"
  _ "github.com/mholt/caddy-events-exec"
  _ "github.com/porech/caddy-maxmind-geolocation"
  _ "github.com/caddy-dns/tencentcloud"
  _ "github.com/tuzzmaniandevil/caddy-dynamic-clientip"
  _ "github.com/fvbommel/caddy-combine-ip-ranges"
  _ "github.com/LeenHawk/caddy-edgeone-ip"
  _ "github.com/monobilisim/caddy-ip-list"
  _ "github.com/WeidiDeng/caddy-cloudflare-ip"
  _ "github.com/xcaddyplugins/caddy-trusted-cloudfront"
  _ "github.com/mholt/caddy-ratelimit"
  _ "github.com/mholt/caddy-webdav"
  _ "github.com/okrc/caddy-uploadcert-tencentcloud"
)
